highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://kndtran.github.io/vitae
author: Khoi-Nguyen Tran

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: 
title: Khoi-Nguyen Tran's resume
name: Khoi-Nguyen Tran
email: christurner@me.com
email_full: mailto:youremail@me.com
website: kndtran.github.io
website_full: https://kndtran.github.io/
#github: trending
#twitter: twitter
#tel: +44 0000 000000
#tel_full: tel:+440000000000
#google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
#address: 44 Perth Street
#postcode: EH3 5BL
city: Melbourne
country: Australia
#google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
