highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://kndtran.github.io/vitae
author: Khoi-Nguyen Tran

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Khoi-Nguyen Tran's resume
name: Khoi-Nguyen Tran
#email: kndtran
#email_full: mailto:youremail@me.com
website: kndtran.com
website_full: http://kndtran.com
gscholar: ihFcT5QAAAAJ
linkedin: kndtran
facebook: kndtran
github: kndtran
twitter: kndtran
#tel: +44 0000 000000
#tel_full: tel:+440000000000
google_maps: 'https://www.google.com.au/maps/place/IBM+Australia+Tower/'
address: 60 City Road
city: Southbank
state: Victoria
postcode: 3006
country: Australia
#google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
